---
- name: Initialize ansible mgmt host localy
  hosts: localhost
  connection: local

  tasks:
  - name: Ensure group "ansible_admins" exists
    group:
      name: ansible_admins
      state: present

  - name: Create Ansible Admin user and Group
    user:
      name: ansible_admin
      comment: "local ansible admin"
      group: ansible_admins

  - name: Create folders with ownership
    file:
      state   : directory
      recurse : yes
      path    : "{{ item }}"
      owner: ansible_admin
      group: ansible_admins
      mode    : "0755"
    with_items:
    - "{{ root_dir }}"
    - "{{ root_dir }}/ansible/private"
    - "{{ root_dir }}/ansible/public/roles"

  - name: Create Files that actually not exists
    file:
      state: touch
      path: "{{ item }}"
    with_items:
      - "{{ root_dir }}/ansible/private/inventory.yml"
      - "{{ root_dir }}/ansible/private/ansible.cfg"

  - name: Set environment variables (ANSIBLE_CONFIG)
    shell: echo "export ANSIBLE_CONFIG={{ root_dir }}/ansible/private/ansible.cfg" >> /etc/profile.d/ansible_envs.sh

  - name: Set environment variables (A)
    shell: echo "export A={{ root_dir }}/ansible/private" >> /etc/profile.d/ansible_envs.sh

  - name: Get All Ansible Roles by definition in config file (Currently Static Value)
    shell: curl -s "https://api.github.com/users/devd4n/repos?per_page=1000" | grep -w clone_url | grep -o '[^"]*\.git' | grep ansible_role
    register: result

  - name: Parse Ansible Roles
    local_action: copy content={{result.stdout}} dest={{ root_dir }}/qu/requirments.yml

  - name: write Ansible Roles to requirements.yml
    lineinfile:
      dest="{{ root_dir }}/qu/requirements.yml"
      regexp='^(.*)$'
      line='- src:\1'
      backrefs=yes

  - name: get Roles from github
    command: ansible-galaxy install -r "{{ root_dir }}/qu/requirements.yml"
